### ISSUE TITLE
Re: 'Main' is redefined in addon/generateheader.cpp

### ISSUE THREAD

**Issue by KennethThompson** [SamVanheer/AngelscriptUtils#1]
First, thanks for making this project available.  It is a game changer for me.

In any event, I am using Codeblocks to build your project and just wanted to point out that I have to ignore the above-referenced cpp file as it redefines 'main' and the compiler complains.

**Comment by SamVanheer** [comment]
generateheader.cpp is part of the Angelscript add_on project generateheader.sln. It isn't supposed to be included in your own projects. I'm sorry this wasn't obvious, i moved all of the addons from their individual directories to add_on because it made writing the CMakeLists a bit simpler at the time. I can move them back if needed.

**Comment by SamVanheer** [comment]
Closing this issue as recommended by Github [archiving guidelines](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories).
